#pragma once

// Local Core2 feasibility port; disabled for all upstream device builds.
#ifndef STACKCHAN_DEVICE_CORE2
#define STACKCHAN_DEVICE_CORE2 0
#endif
#if STACKCHAN_DEVICE_CORE2
#define STACKCHAN_DEVICE_DISPLAY_NAME "StackChan Core2 Pocket"
#define STACKCHAN_FIRMWARE_NAME "stackchan-core2-pocket"
#define STACKCHAN_FIRMWARE_VERSION "0.3.32"
#endif

#if !defined(STACKCHAN_RELEASE_BUILD) && __has_include("config_private.h")
#include "config_private.h"
#endif

#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif

#ifndef WIFI_SSID_2
#define WIFI_SSID_2 ""
#endif

#ifndef WIFI_PASSWORD_2
#define WIFI_PASSWORD_2 ""
#endif

#ifndef STACKCHAN_DEVICE_STOPWATCH
#define STACKCHAN_DEVICE_STOPWATCH 0
#endif

#ifndef STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define STACKCHAN_DEVICE_ATOMS3R_CHATBOT 0
#endif

#ifndef STACKCHAN_DEVICE_CORES3
#if STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define STACKCHAN_DEVICE_CORES3 0
#else
#define STACKCHAN_DEVICE_CORES3 1
#endif
#endif

#ifndef STACKCHAN_HAS_STACKCHAN_BSP
#define STACKCHAN_HAS_STACKCHAN_BSP STACKCHAN_DEVICE_CORES3
#endif

#ifndef STOPWATCH_STATUS_LED_ENABLED
#define STOPWATCH_STATUS_LED_ENABLED 0
#endif

#ifndef STACKCHAN_HAS_SERVO
#define STACKCHAN_HAS_SERVO STACKCHAN_DEVICE_CORES3
#endif

#ifndef STACKCHAN_HAS_CAMERA
#define STACKCHAN_HAS_CAMERA STACKCHAN_DEVICE_CORES3
#endif

#ifndef STACKCHAN_HAS_BACK_TOUCH
#define STACKCHAN_HAS_BACK_TOUCH STACKCHAN_DEVICE_CORES3
#endif

#ifndef STACKCHAN_HAS_SCREEN_TOUCH_PETTING
#define STACKCHAN_HAS_SCREEN_TOUCH_PETTING STACKCHAN_DEVICE_STOPWATCH
#endif

#ifndef STACKCHAN_HAS_HAPTIC
#define STACKCHAN_HAS_HAPTIC STACKCHAN_DEVICE_STOPWATCH
#endif

#ifndef STACKCHAN_ROUND_DISPLAY
#define STACKCHAN_ROUND_DISPLAY STACKCHAN_DEVICE_STOPWATCH
#endif

#ifndef STACKCHAN_PHONE_CAMERA_REMOTE_ENABLED
#define STACKCHAN_PHONE_CAMERA_REMOTE_ENABLED STACKCHAN_DEVICE_STOPWATCH
#endif

#ifndef STACKCHAN_SMALL_DISPLAY
#define STACKCHAN_SMALL_DISPLAY STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#endif

#ifndef STACKCHAN_CLASSIC_FACE_ENABLED
#define STACKCHAN_CLASSIC_FACE_ENABLED 0
#endif

#ifndef STACKCHAN_PET_ANIMATION_ENABLED
#define STACKCHAN_PET_ANIMATION_ENABLED \
  (!STACKCHAN_CLASSIC_FACE_ENABLED && \
   (STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_DEVICE_CORES3 || STACKCHAN_DEVICE_ATOMS3R_CHATBOT))
#endif

#ifndef STACKCHAN_GURUGURU_FACE_ENABLED
#define STACKCHAN_GURUGURU_FACE_ENABLED \
  (!STACKCHAN_CLASSIC_FACE_ENABLED && \
   (STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_DEVICE_CORES3 || STACKCHAN_DEVICE_ATOMS3R_CHATBOT))
#endif

#ifndef STACKCHAN_GURUGURU_IMU_ENABLED
#define STACKCHAN_GURUGURU_IMU_ENABLED \
  (!STACKCHAN_CLASSIC_FACE_ENABLED && \
   (STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_DEVICE_CORES3 || STACKCHAN_DEVICE_ATOMS3R_CHATBOT))
#endif

#ifndef STACKCHAN_GURUGURU_CANVAS_CACHE_ENABLED
#define STACKCHAN_GURUGURU_CANVAS_CACHE_ENABLED STACKCHAN_GURUGURU_FACE_ENABLED
#endif

#ifndef STACKCHAN_GURUGURU_FACE_COUNT
#if STACKCHAN_DEVICE_STOPWATCH
#define STACKCHAN_GURUGURU_FACE_COUNT 9
#else
#define STACKCHAN_GURUGURU_FACE_COUNT 17
#endif
#endif

#ifndef STACKCHAN_GURUGURU_FACE_CENTER_INDEX
#if STACKCHAN_DEVICE_STOPWATCH
#define STACKCHAN_GURUGURU_FACE_CENTER_INDEX 8
#else
#define STACKCHAN_GURUGURU_FACE_CENTER_INDEX 16
#endif
#endif

#define GURUGURU_IMU_UPDATE_INTERVAL_MS 40
#define GURUGURU_IMU_DEADZONE_G 0.18f
#define GURUGURU_IMU_STOPWATCH_DEADZONE_G 0.28f
#if STACKCHAN_DEVICE_STOPWATCH
#define GURUGURU_IMU_EMA_ALPHA 0.25f
#else
#define GURUGURU_IMU_EMA_ALPHA 0.18f
#endif
#define GURUGURU_IMU_MAX_SAMPLE_DELTA_G 0.80f
#define GURUGURU_IMU_MIN_ACCEL_MAG_G 0.65f
#define GURUGURU_IMU_MAX_ACCEL_MAG_G 1.35f
#define GURUGURU_IMU_CORES3_GRID_EDGE_G 0.50f
#if STACKCHAN_DEVICE_STOPWATCH
#define GURUGURU_IMU_DIRECTION_STABLE_SAMPLES 2
#else
#define GURUGURU_IMU_DIRECTION_STABLE_SAMPLES 3
#endif
#define GURUGURU_IMU_VERTICAL_GAIN 1.8f
#if STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_DEVICE_ATOMS3R_CHATBOT || STACKCHAN_DEVICE_CORES3
#define GURUGURU_DIZZY_FRAME_COUNT 23
#else
#define GURUGURU_DIZZY_FRAME_COUNT 24
#endif
#define GURUGURU_DIZZY_FRAME_INTERVAL_MS 167
#define GURUGURU_DIZZY_WINDOW_MS 2000
#if STACKCHAN_DEVICE_CORES3
#define GURUGURU_DIZZY_TOTAL_STEPS 32
#define GURUGURU_DIZZY_BIAS_STEPS 24
#elif STACKCHAN_DEVICE_STOPWATCH
#define GURUGURU_DIZZY_TOTAL_STEPS 16
#define GURUGURU_DIZZY_BIAS_STEPS 12
#else
#define GURUGURU_DIZZY_TOTAL_STEPS 22
#define GURUGURU_DIZZY_BIAS_STEPS 4
#endif
#define GURUGURU_DIZZY_COOLDOWN_MS 3000
#define GURUGURU_AFFECTION_STEP_COUNT 8
#if STACKCHAN_DEVICE_CORES3
#define GURUGURU_AFFECTION_MIN_PROJECTED_STEPS 14
#define GURUGURU_AFFECTION_RED_PROJECTED_STEPS 30
#else
#define GURUGURU_AFFECTION_MIN_PROJECTED_STEPS 7
#define GURUGURU_AFFECTION_RED_PROJECTED_STEPS 15
#endif
#define GURUGURU_AFFECTION_REWARD_DELTA 1
#define GURUGURU_AFFECTION_DANGER_BONUS_DELTA 1
#define GURUGURU_DIZZY_AFFECTION_DELTA -10
#if STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define GURUGURU_IMU_DIZZY_SHAKE_THRESHOLD_G 0.40f
#define GURUGURU_IMU_DIZZY_SHAKE_MS 900
#define GURUGURU_IMU_DIZZY_SHAKE_GRACE_MS 700
#else
#define GURUGURU_IMU_DIZZY_SHAKE_THRESHOLD_G 0.20f
#define GURUGURU_IMU_DIZZY_SHAKE_MS 4000
#define GURUGURU_IMU_DIZZY_SHAKE_GRACE_MS 450
#endif

#ifndef STACKCHAN_IMU_PETTING
#define STACKCHAN_IMU_PETTING 0
#endif

#ifndef STACKCHAN_HAS_ATOMIC_ECHO_BASE
#define STACKCHAN_HAS_ATOMIC_ECHO_BASE STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#endif

#ifndef AP_SSID
#if STACKCHAN_DEVICE_STOPWATCH
#define AP_SSID "StopWatch"
#elif STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define AP_SSID "AtomS3R"
#else
#define AP_SSID "StackChan-Direct"
#endif
#endif

#ifndef AP_PASSWORD
#if STACKCHAN_DEVICE_STOPWATCH
#define AP_PASSWORD "stopwatch123"
#elif STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define AP_PASSWORD "atoms3r123"
#else
#define AP_PASSWORD "stackchan123"
#endif
#endif
#define AP_IP_0 192
#define AP_IP_1 168
#define AP_IP_2 4
#define AP_IP_3 1

#define WIFI_STATUS_CHECK_INTERVAL_MS 1000
#define WIFI_CONNECT_RETRY_MS 12000
#define WIFI_CONNECT_ATTEMPTS_PER_CREDENTIAL 2

#define WS_PORT 8080
#define WS_PATH "/"

#ifndef STREETPASS_LEGACY_DEFAULT_NAME
#define STREETPASS_LEGACY_DEFAULT_NAME "Stack-chan"
#endif

#ifndef STREETPASS_DEFAULT_NAME
#if STACKCHAN_DEVICE_STOPWATCH
#define STREETPASS_DEFAULT_NAME "StopWatch"
#elif STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define STREETPASS_DEFAULT_NAME "ｽﾀｯｸﾁｬﾝ ミニマル"
#else
#define STREETPASS_DEFAULT_NAME STREETPASS_LEGACY_DEFAULT_NAME
#endif
#endif

#ifndef STACKCHAN_FIRMWARE_NAME
#define STACKCHAN_FIRMWARE_NAME "stackchan-pet-fw"
#endif

#ifndef STACKCHAN_FIRMWARE_VERSION
#define STACKCHAN_FIRMWARE_VERSION "dev"
#endif

#ifndef STACKCHAN_APP_PROTOCOL_VERSION
#define STACKCHAN_APP_PROTOCOL_VERSION 2
#endif

#ifndef STACKCHAN_DEVICE_DISPLAY_NAME
#define STACKCHAN_DEVICE_DISPLAY_NAME STREETPASS_DEFAULT_NAME
#endif

#ifndef STREETPASS_BLE_DEVICE_NAME
#if STACKCHAN_DEVICE_STOPWATCH
#define STREETPASS_BLE_DEVICE_NAME "StopWatch StreetPass"
#else
#define STREETPASS_BLE_DEVICE_NAME "StackChan StreetPass"
#endif
#endif

#ifndef STREETPASS_DEFAULT_MESSAGE
#define STREETPASS_DEFAULT_MESSAGE "Konnichiwa"
#endif

#define FACE_IDLE_PATH "/idle.png"
#define FACE_LISTEN_PATH "/listen.png"
#define FACE_TALK_0_PATH "/talk_0.png"
#define FACE_TALK_1_PATH "/talk_1.png"
#define FACE_IDLE_GUARDED_0_PATH "/idle_guarded_0.png"
#define FACE_IDLE_ATTACHED_0_PATH "/idle_attached_0.png"
#define FACE_BLINK_GUARDED_0_PATH "/blink_guarded_0.png"
#define FACE_BLINK_ATTACHED_0_PATH "/blink_attached_0.png"
#define FACE_TALK_GUARDED_0_PATH "/talk_guarded_0.png"
#define FACE_TALK_GUARDED_1_PATH "/talk_guarded_1.png"
#define FACE_TALK_ATTACHED_0_PATH "/talk_attached_0.png"
#define FACE_TALK_ATTACHED_1_PATH "/talk_attached_1.png"
#define FACE_BAD_0_PATH "/bad_0.png"
#define FACE_BAD_1_PATH "/bad_1.png"
#define FACE_GOOD_0_PATH "/good_0.png"
#define FACE_GOOD_1_PATH "/good_1.png"
#define FACE_GOOD_BLINK_PATH "/good_blink.png"
#define FACE_PHOTO_0_PATH "/photo_0.png"
#define FACE_PHOTO_1_PATH "/photo_1.png"
#define FACE_PHOTO_BLINK_PATH "/photo_blink.png"
#define FACE_PHOTO_BLINK_TALK_PATH "/photo_blink_talk.png"
#define FACE_PHOTO_MASTER_0_PATH "/photo_master_0.png"
#define FACE_PHOTO_MASTER_1_PATH "/photo_master_1.png"
#define FACE_NADENADE_0_PATH "/nadenade_0.png"
#define FACE_NADENADE_1_PATH "/nadenade_1.png"
#define FACE_PET_GUARDED_0_PATH "/pet_guarded_0.png"
#define FACE_PET_GUARDED_1_PATH "/pet_guarded_1.png"
#define FACE_PET_BLINK_GUARDED_0_PATH "/pet_blink_guarded_0.png"
#define FACE_PET_ATTACHED_0_PATH "/pet_attached_0.png"
#define FACE_PET_ATTACHED_1_PATH "/pet_attached_1.png"
#define FACE_PET_BLINK_ATTACHED_0_PATH "/pet_blink_attached_0.png"
#define FACE_FURIFURI_0_PATH "/furifuri_0.png"
#define FACE_FURIFURI_1_PATH "/furifuri_1.png"
#define FACE_SHAKE_GUARDED_0_PATH "/shake_guarded_0.png"
#define FACE_SHAKE_GUARDED_1_PATH "/shake_guarded_1.png"
#define FACE_SHAKE_ATTACHED_0_PATH "/shake_attached_0.png"
#define FACE_SHAKE_ATTACHED_1_PATH "/shake_attached_1.png"
#define FACE_BLINK_PATH "/blink.png"
#define FACE_SMILE_PATH "/smile.png"
#define FACE_TIRED_0_PATH "/tired_0.png"
#define FACE_TIRED_TALK_PATH "/tired_talk.png"
#define FACE_TIRED_BLINK_PATH "/tired_blink.png"
#define FACE_EXHAUSTED_0_PATH "/exhausted_0.png"
#define FACE_EXHAUSTED_TALK_PATH "/exhausted_talk.png"
#define FACE_EXHAUSTED_BLINK_PATH "/exhausted_blink.png"
#define FACE_LOW_POWER_0_PATH "/low_power_0.png"
#define FACE_LOW_POWER_TALK_PATH "/low_power_talk.png"
#define FACE_LOW_POWER_BLINK_PATH "/low_power_blink.png"

#if STACKCHAN_SMALL_DISPLAY
#define FACE_IMAGE_WIDTH 128
#define FACE_IMAGE_HEIGHT 128
#elif STACKCHAN_ROUND_DISPLAY
#define FACE_IMAGE_WIDTH 386
#define FACE_IMAGE_HEIGHT 386
#else
#define FACE_IMAGE_WIDTH 240
#define FACE_IMAGE_HEIGHT 240
#endif
#ifndef FACE_CACHE_WIDTH
#if STACKCHAN_DEVICE_STOPWATCH
#define FACE_CACHE_WIDTH 360
#else
#define FACE_CACHE_WIDTH FACE_IMAGE_WIDTH
#endif
#endif
#ifndef FACE_CACHE_HEIGHT
#if STACKCHAN_DEVICE_STOPWATCH
#define FACE_CACHE_HEIGHT 360
#else
#define FACE_CACHE_HEIGHT FACE_IMAGE_HEIGHT
#endif
#endif
#if STACKCHAN_ROUND_DISPLAY
#define ROUND_FACE_IMAGE_MAX_SCALE 1.0f
#else
#define ROUND_FACE_IMAGE_MAX_SCALE 2.0f
#endif
#define ROUND_FACE_IMAGE_MARGIN_PX 30

#ifndef GURUGURU_DIZZY_CANVAS_SCALE
#define GURUGURU_DIZZY_CANVAS_SCALE 0.93f
#endif

#ifndef GURUGURU_DIZZY_CANVAS_SIZE
#if STACKCHAN_ROUND_DISPLAY
#define GURUGURU_DIZZY_CANVAS_SIZE 346
#else
#define GURUGURU_DIZZY_CANVAS_SIZE FACE_IMAGE_WIDTH
#endif
#endif

#ifndef GURUGURU_FACE_CANVAS_SIZE
#if STACKCHAN_ROUND_DISPLAY
#define GURUGURU_FACE_CANVAS_SIZE 366
#else
#define GURUGURU_FACE_CANVAS_SIZE FACE_IMAGE_WIDTH
#endif
#endif

#ifndef CLOCK_DISPLAY_ENABLED
#define CLOCK_DISPLAY_ENABLED STACKCHAN_DEVICE_STOPWATCH
#endif
#define CLOCK_DISPLAY_UPDATE_MS 1000
#ifndef STACKCHAN_TIMEZONE_NAME
#define STACKCHAN_TIMEZONE_NAME "Asia/Tokyo"
#endif
#ifndef STACKCHAN_TIMEZONE_POSIX
#define STACKCHAN_TIMEZONE_POSIX "JST-9"
#endif
#define CLOCK_DISPLAY_UTC_OFFSET_MINUTES 540

#ifndef STEP_COUNTER_ENABLED
#define STEP_COUNTER_ENABLED STACKCHAN_DEVICE_STOPWATCH
#endif
#define STEP_COUNTER_HISTORY_DAYS 30
#define STEP_COUNTER_DAY_START_HOUR 4
#define STEP_COUNTER_SAVE_STEP_DELTA 10
#define STEP_COUNTER_SAVE_INTERVAL_MS 60000
#ifndef STEP_COUNTER_STEP_SCALE_NUMERATOR
#if STACKCHAN_DEVICE_STOPWATCH
#define STEP_COUNTER_STEP_SCALE_NUMERATOR 17
#else
#define STEP_COUNTER_STEP_SCALE_NUMERATOR 1
#endif
#endif
#ifndef STEP_COUNTER_STEP_SCALE_DENOMINATOR
#if STACKCHAN_DEVICE_STOPWATCH
#define STEP_COUNTER_STEP_SCALE_DENOMINATOR 10
#else
#define STEP_COUNTER_STEP_SCALE_DENOMINATOR 1
#endif
#endif
#ifndef STEP_COUNTER_WALK_START_CANDIDATES
#if STACKCHAN_DEVICE_STOPWATCH
#define STEP_COUNTER_WALK_START_CANDIDATES 3
#else
#define STEP_COUNTER_WALK_START_CANDIDATES 2
#endif
#endif
#ifndef STEP_COUNTER_MIN_STEP_INTERVAL_MS
#if STACKCHAN_DEVICE_STOPWATCH
#define STEP_COUNTER_MIN_STEP_INTERVAL_MS 260
#else
#define STEP_COUNTER_MIN_STEP_INTERVAL_MS 220
#endif
#endif
#ifndef STEP_COUNTER_MAX_STEP_INTERVAL_MS
#define STEP_COUNTER_MAX_STEP_INTERVAL_MS 1650
#endif
#ifndef STEP_COUNTER_WALKING_TIMEOUT_MS
#define STEP_COUNTER_WALKING_TIMEOUT_MS 2200
#endif
#ifndef STEP_COUNTER_DYNAMIC_ENERGY_MULTIPLIER
#if STACKCHAN_DEVICE_STOPWATCH
#define STEP_COUNTER_DYNAMIC_ENERGY_MULTIPLIER 2.4f
#else
#define STEP_COUNTER_DYNAMIC_ENERGY_MULTIPLIER 2.0f
#endif
#endif
#ifndef STEP_COUNTER_DYNAMIC_ENERGY_MIN
#if STACKCHAN_DEVICE_STOPWATCH
#define STEP_COUNTER_DYNAMIC_ENERGY_MIN 0.022f
#else
#define STEP_COUNTER_DYNAMIC_ENERGY_MIN 0.012f
#endif
#endif
#ifndef STEP_COUNTER_LOW_THRESHOLD_RATIO
#define STEP_COUNTER_LOW_THRESHOLD_RATIO 0.42f
#endif
#ifndef DISPLAY_OFF_LIGHT_SLEEP_ENABLED
#define DISPLAY_OFF_LIGHT_SLEEP_ENABLED STACKCHAN_DEVICE_STOPWATCH
#endif
#ifndef DISPLAY_OFF_CPU_FREQ_MHZ
#define DISPLAY_OFF_CPU_FREQ_MHZ 80
#endif
#ifndef DISPLAY_OFF_LIGHT_SLEEP_WAKE_MARGIN_MS
#define DISPLAY_OFF_LIGHT_SLEEP_WAKE_MARGIN_MS 2
#endif
#ifndef DISPLAY_OFF_LIGHT_SLEEP_MIN_MS
#define DISPLAY_OFF_LIGHT_SLEEP_MIN_MS 3
#endif
#define STEP_SYNC_SCHEMA_VERSION 1
#define STEP_SYNC_UPDATE_STEP_DELTA 10
#define STEP_SYNC_UPDATE_INTERVAL_MS 60000
#ifndef STEP_AFFECTION_REWARD_ENABLED
#define STEP_AFFECTION_REWARD_ENABLED STEP_COUNTER_ENABLED
#endif
#define STEP_AFFECTION_STEPS_PER_REWARD 1000
#define STEP_AFFECTION_DELTA_PER_REWARD 3

#define LIP_SYNC_INTERVAL_MS 300
#define BLINK_MIN_INTERVAL_MS 3000
#define BLINK_MAX_INTERVAL_MS 7000
#define GURUGURU_BLINK_MIN_INTERVAL_MS 2000
#define GURUGURU_BLINK_MAX_INTERVAL_MS 5000
#define BLINK_DURATION_MS 300
#ifndef STACKCHAN_VOICE_SPRITE_ANIMATION_ENABLED
#define STACKCHAN_VOICE_SPRITE_ANIMATION_ENABLED \
  (!STACKCHAN_CLASSIC_FACE_ENABLED && \
   (STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_DEVICE_CORES3 || STACKCHAN_DEVICE_ATOMS3R_CHATBOT))
#endif
#define VOICE_SPRITE_EYE_FRAME_COUNT 4
#define VOICE_SPRITE_MOUTH_FRAME_COUNT 4
#define VOICE_SPRITE_BLINK_MIN_FPS 14
#define VOICE_SPRITE_BLINK_MAX_FPS 20
#define VOICE_SPRITE_MOUTH_FRAME_INTERVAL_MS 83
#define VOICE_SPRITE_PETTING_EYE_INTERVAL_MS 167
#define VOICE_SPRITE_MOUTH_HOLD_MS 240
#define VOICE_SPRITE_PEAK_SILENCE 900
#define VOICE_SPRITE_PEAK_FULL_OPEN 20000
#define CLASSIC_FACE_MOUTH_LEVEL_COUNT 8
#define CLASSIC_FACE_MOUTH_FRAME_INTERVAL_MS 160
#define CLASSIC_FACE_MOUTH_HOLD_MS 100
#define CLASSIC_FACE_MOUTH_ENVELOPE_SILENCE 0
#define CLASSIC_FACE_MOUTH_ENVELOPE_FULL_OPEN 12000
#define CLASSIC_FACE_MOUTH_MIN_ACTIVE_LEVEL 2
#define CLASSIC_FACE_MOUTH_MIN_WIDTH 60
#define CLASSIC_FACE_MOUTH_MAX_HEIGHT 42
#ifndef CLASSIC_FACE_LIP_SYNC_DIAG_LOG_ENABLED
#define CLASSIC_FACE_LIP_SYNC_DIAG_LOG_ENABLED 0
#endif
#define IDLE_SMILE_MIN_INTERVAL_MS 8000
#define IDLE_SMILE_MAX_INTERVAL_MS 20000
#define IDLE_SMILE_DURATION_MS 1500

#define SERVO_UPDATE_INTERVAL_MS 30
#define SERVO_PAN_MIN 45
#define SERVO_PAN_MAX 135
#define SERVO_TILT_MIN 60
#define SERVO_TILT_MAX 120
#define SERVO_PAN_CENTER 90
#define SERVO_TILT_CENTER 82
#define SERVO_OUTPUT_ENABLED 1
#define SERVO_OUTPUT_SPEED 300
#define SERVO_AXIS_SETTLE_MS 350
#define SERVO_MIC_QUIET_AFTER_MS 500
#define SERVO_STARTUP_OUTPUT_DELAY_MS 0
#define LISTENING_NOD_FIRST_MIN_INTERVAL_MS 1200
#define LISTENING_NOD_FIRST_MAX_INTERVAL_MS 1500
#define LISTENING_NOD_MIN_INTERVAL_MS 2100
#define LISTENING_NOD_MAX_INTERVAL_MS 4200
#define LISTENING_NOD_DOWN_MS 240
#define LISTENING_NOD_UP_MS 280
#define LISTENING_NOD_TILT_DELTA 14
#define LISTENING_NOD_ENABLED 0

#define INTERACTION_STARTUP_IGNORE_MS 1000
#define OVERLAY_BUTTON_SHORT_PRESS_MAX_MS 800
#define OVERLAY_BUTTON_MOVE_LIMIT_PX 22
#define OVERLAY_BUTTON_RELEASE_SLOP_PX 8
#define STOPWATCH_OVERLAY_BUTTON_TOUCH_RADIUS_PX 38
#define CORES3_OVERLAY_BUTTON_TOUCH_WIDTH_PX 56
#define PET_TOUCH_RELEASE_GRACE_MS 1000
#define PET_BUTTON_RELEASE_LINGER_MS 2000
#define BACK_TOUCH_INTENSITY_THRESHOLD 2
#define BACK_TOUCH_REQUIRED_MS 140
#define BACK_TOUCH_RELEASE_MS 180
#define BACK_TOUCH_STARTUP_RELEASE_MS 1000
#define BACK_TOUCH_GURUGURU_TAP_MIN_MS 30
#define BACK_TOUCH_GURUGURU_TAP_MAX_MS 280
#define BACK_TOUCH_GURUGURU_DOUBLE_TAP_MS 420
#define BACK_TOUCH_GURUGURU_HOLD_MS 650
#define SCREEN_PETTING_RADIUS_PX 152
#define SCREEN_PETTING_REQUIRED_MS 140
#define SCREEN_PETTING_DRAG_DISTANCE_PX 18
#define SCREEN_PETTING_RELEASE_MS 120
#define PET_ANIMATION_START_INTERVAL_MS 100
#define PET_ANIMATION_LOOP_INTERVAL_MS 167
#define PET_ANIMATION_END_INTERVAL_MS 100
#define PET_ANIMATION_AFTER_INTERVAL_MS 125
#define PET_ANIMATION_AFTER_HOLD_MS 500
#ifndef PET_ANIMATION_TOUCH_CENTER_HALF_WIDTH_PX
#define PET_ANIMATION_TOUCH_CENTER_HALF_WIDTH_PX (SCREEN_PETTING_RADIUS_PX / 4)
#endif
#ifndef PET_ANIMATION_LONG_THRESHOLD_MS
#define PET_ANIMATION_LONG_THRESHOLD_MS 3000
#endif
#ifndef PETTING_SHORT_AFFECTION_DELTA
#define PETTING_SHORT_AFFECTION_DELTA -5
#endif
#ifndef VOICE_PETTING_AFFECTION_DELTA
#define VOICE_PETTING_AFFECTION_DELTA 5
#endif
#define PET_MOVE_MIN_INTERVAL_MS 130
#define PET_MOVE_MAX_INTERVAL_MS 280
#define PET_BIG_MOVE_CHANCE_PERCENT 38
#define PET_SMALL_PAN_MIN 10
#define PET_SMALL_PAN_MAX 22
#define PET_BIG_PAN_MIN 24
#define PET_BIG_PAN_MAX 38
#define PET_SMALL_TILT_MIN 84
#define PET_SMALL_TILT_MAX 88
#define PET_BIG_TILT_MIN 87
#define PET_BIG_TILT_MAX 90
#define PET_MAX_PITCH_LIFT 120
#ifndef SHAKE_UPDATE_INTERVAL_MS
#define SHAKE_UPDATE_INTERVAL_MS 20
#endif
#ifndef SHAKE_ACC_THRESHOLD_G
#if STACKCHAN_DEVICE_STOPWATCH
#define SHAKE_ACC_THRESHOLD_G 0.80f
#else
#define SHAKE_ACC_THRESHOLD_G 1.1f
#endif
#endif
#ifndef SHAKE_GYRO_THRESHOLD_DPS
#if STACKCHAN_DEVICE_STOPWATCH
#define SHAKE_GYRO_THRESHOLD_DPS 220.0f
#else
#define SHAKE_GYRO_THRESHOLD_DPS 280.0f
#endif
#endif
#ifndef SHAKE_REQUIRED_SAMPLES
#if STACKCHAN_DEVICE_STOPWATCH
#define SHAKE_REQUIRED_SAMPLES 2
#else
#define SHAKE_REQUIRED_SAMPLES 2
#endif
#endif
#ifndef SHAKE_GYRO_ACCEL_GATE_G
#define SHAKE_GYRO_ACCEL_GATE_G 0.28f
#endif
#ifndef SHAKE_ACCEL_GYRO_GATE_DPS
#define SHAKE_ACCEL_GYRO_GATE_DPS 120.0f
#endif
#ifndef SHAKE_FACE_HOLD_MS
#define SHAKE_FACE_HOLD_MS 1200
#endif
#ifndef SHAKE_ANIMATION_INTERVAL_MS
#define SHAKE_ANIMATION_INTERVAL_MS 167
#endif
#ifndef SHAKE_RECOVERY_FRAME_INTERVAL_MS
#define SHAKE_RECOVERY_FRAME_INTERVAL_MS 125
#endif
#ifndef SHAKE_RECOVERY_CLOSED_HOLD_MS
#define SHAKE_RECOVERY_CLOSED_HOLD_MS 300
#endif
#ifndef SHAKE_COOLDOWN_MS
#if STACKCHAN_DEVICE_STOPWATCH
#define SHAKE_COOLDOWN_MS 1000
#else
#define SHAKE_COOLDOWN_MS 1800
#endif
#endif
#define IMU_PETTING_ACC_THRESHOLD_G 0.35f
#define IMU_PETTING_GYRO_THRESHOLD_DPS 120.0f
#define IMU_PETTING_REQUIRED_SAMPLES 2
#define IMU_PETTING_COOLDOWN_MS 2200
#define SHAKE_MOTION_INTERVAL_MS 80
#define SHAKE_MOTION_PAN_MAX_DEGREES 24
#define SHAKE_MOTION_TILT_UP_DEGREES 14
#define SHAKE_MOTION_TILT_DOWN_DEGREES 18
#define SHAKE_MOTION_GYRO_PAN_SCALE 0.030f
#define SHAKE_MOTION_GYRO_TILT_SCALE 0.020f
#define HAPTIC_PETTING_START_LEVEL 96
#define HAPTIC_PETTING_START_MS 45
#define HAPTIC_SHAKE_LEVEL 128
#define HAPTIC_SHAKE_MS 70
#define INTERACTION_SERVO_START_DELAY_MS 120
#define SHAKE_SERVO_START_DELAY_MS 40

#define AUDIO_SAMPLE_RATE 16000
#define AUDIO_CHANNELS 1
#define AUDIO_BITS_PER_SAMPLE 16
#define MIC_SEND_INTERVAL_MS 40
#define AUDIO_MIC_CATCHUP_MAX_CHUNKS 3
#define AUDIO_MIC_DIAG_INTERVAL_MS 1000
#if STACKCHAN_DEVICE_ATOMS3R_CHATBOT || STACKCHAN_DEVICE_CORE2
#define AUDIO_MIC_MAGNIFICATION 1
#define AUDIO_MIC_NOISE_FILTER_LEVEL 0
#define AUDIO_MIC_OVERSAMPLING 1
#define AUDIO_MIC_SOFTWARE_GAIN_Q8 256
#define AUDIO_MIC_GATE_ENABLED 0
#define AUDIO_MIC_GATE_PEAK_THRESHOLD 20
#else
#define AUDIO_MIC_MAGNIFICATION 4
#define AUDIO_MIC_NOISE_FILTER_LEVEL 32
#define AUDIO_MIC_OVERSAMPLING 2
#define AUDIO_MIC_SOFTWARE_GAIN_Q8 160
#define AUDIO_MIC_GATE_ENABLED 1
#define AUDIO_MIC_GATE_PEAK_THRESHOLD 900
#endif
#define AUDIO_MIC_CLIP_THRESHOLD 30000
#define AUDIO_MIC_GATE_PREROLL_MS 500
#define AUDIO_MIC_GATE_OPEN_HOLD_MS 1000
#define AUDIO_CHUNK_MS 40
#define AUDIO_CHUNK_SAMPLES ((AUDIO_SAMPLE_RATE * AUDIO_CHUNK_MS) / 1000)
#define AUDIO_CHUNK_BYTES (AUDIO_CHUNK_SAMPLES * sizeof(int16_t))
#define AUDIO_MIC_GATE_PREROLL_CHUNKS ((AUDIO_MIC_GATE_PREROLL_MS + AUDIO_CHUNK_MS - 1) / AUDIO_CHUNK_MS)
#define AUDIO_MIC_PACKET_HEADER_BYTES 16
#define AUDIO_MIC_PACKET_BYTES (AUDIO_MIC_PACKET_HEADER_BYTES + AUDIO_CHUNK_BYTES)
#define AUDIO_MIC_PACKET_FLAG_START 0x0001
#define AUDIO_MIC_TX_BUFFER_COUNT 128
#define AUDIO_MIC_CAPTURE_TASK_STACK_WORDS 6144
#define AUDIO_MIC_CAPTURE_TASK_PRIORITY 3
#define AUDIO_MIC_CAPTURE_GAP_TOLERANCE_MS 20
#ifndef AUDIO_SPEAKER_PLAYBACK_TASK_ENABLED
#define AUDIO_SPEAKER_PLAYBACK_TASK_ENABLED \
  (STACKCHAN_VOICE_SPRITE_ANIMATION_ENABLED || STACKCHAN_CLASSIC_FACE_ENABLED)
#endif
#define AUDIO_SPEAKER_PLAYBACK_TASK_STACK_WORDS 4096
#define AUDIO_SPEAKER_PLAYBACK_TASK_PRIORITY 4
#define AUDIO_SPEAKER_PLAYBACK_TASK_CORE 0
#if STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_CLASSIC_FACE_ENABLED
#define AUDIO_PLAYBACK_CHUNK_MS 80
#else
#define AUDIO_PLAYBACK_CHUNK_MS 60
#endif
#define AUDIO_PLAYBACK_CHUNK_SAMPLES ((AUDIO_SAMPLE_RATE * AUDIO_PLAYBACK_CHUNK_MS) / 1000)
#define AUDIO_PLAYBACK_CHUNK_BYTES (AUDIO_PLAYBACK_CHUNK_SAMPLES * sizeof(int16_t))
#define AUDIO_MIC_BUFFER_COUNT 4
#define AUDIO_SPEAKER_BUFFER_COUNT 8
#define AUDIO_SPEAKER_QUEUE_TARGET_CHUNKS 2
#if STACKCHAN_DEVICE_STOPWATCH || STACKCHAN_CLASSIC_FACE_ENABLED
#define AUDIO_SPEAKER_MAX_QUEUE_PER_UPDATE 2
#define AUDIO_PLAYBACK_PREBUFFER_MS 360
#else
#define AUDIO_SPEAKER_MAX_QUEUE_PER_UPDATE 1
#define AUDIO_PLAYBACK_PREBUFFER_MS 180
#endif
#define AUDIO_SPEAKER_CHANNEL 0
#if STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define AUDIO_SPEAKER_VOLUME 120
#else
#define AUDIO_SPEAKER_VOLUME 180
#endif
#define AUDIO_PLAYBACK_PREBUFFER_BYTES ((AUDIO_SAMPLE_RATE * AUDIO_PLAYBACK_PREBUFFER_MS / 1000) * sizeof(int16_t))
#define AUDIO_RX_RING_BYTES (512 * 1024)
#if STACKCHAN_DEVICE_STOPWATCH
#define AUDIO_RX_BACKPRESSURE_TIMEOUT_MS 3000
#else
#define AUDIO_RX_BACKPRESSURE_TIMEOUT_MS 0
#endif
#define AUDIO_IDLE_DRAIN_GRACE_MS 300
#define AUDIO_SPEAKER_TO_MIC_DELAY_MS 250
#define AUDIO_AFTER_CAPTURE_SPEAKER_DELAY_MS 250
#define AUDIO_WS_CONNECT_SETTLE_MS 1200
#define CAMERA_PAUSE_MIC_DURING_CAPTURE 1
#define PHONE_CAMERA_REQUEST_TIMEOUT_MS 30000
#define PHONE_CAMERA_LENS_REQUEST_TIMEOUT_MS 10000
#define PHONE_CAMERA_FEEDBACK_MS 900
#define PHONE_CAMERA_PROTOCOL_VERSION 1
#define PHONE_CAMERA_LONG_PRESS_MS 800
#define PHONE_CAMERA_LONG_PRESS_MOVE_PX 18
#define PHONE_CAMERA_HAPTIC_SUCCESS_LEVEL 104
#define PHONE_CAMERA_HAPTIC_SUCCESS_MS 45
#define PHONE_CAMERA_HAPTIC_FAILURE_LEVEL 156
#define PHONE_CAMERA_HAPTIC_FAILURE_MS 110

#define SPEECH_BUBBLE_PROTOCOL_VERSION 1
#define SPEECH_BUBBLE_CAPABILITY "display.speech_bubble.v1"
#define SPEECH_BUBBLE_MAX_SEQUENCE_ID_BYTES 64
#define SPEECH_BUBBLE_MAX_TEXT_BYTES 512
#define SPEECH_BUBBLE_MAX_QUEUED_CUES 16
#define SPEECH_BUBBLE_MAX_PCM_BYTES (8UL * 1024UL * 1024UL)
#define SPEECH_BUBBLE_DEFAULT_HOLD_MS 800
#define SPEECH_BUBBLE_MAX_HOLD_MS 5000
#define SPEECH_BUBBLE_STALL_TIMEOUT_MS 15000
#define SPEECH_BUBBLE_PRE_SPEAKING_HOLD_MS 500
#define SPEECH_BUBBLE_RENDER_RETRY_MS 80

#define HTTP_PORT 80
#define USB_SERIAL_PROTOCOL_ENABLED 1
#define USB_SERIAL_BAUD 921600
#define USB_SERIAL_LINE_BUFFER_BYTES 1024
#if STACKCHAN_DEVICE_CORE2
#define USB_SERIAL_RX_BUFFER_BYTES 16384
#elif STACKCHAN_DEVICE_STOPWATCH
#define USB_SERIAL_RX_BUFFER_BYTES 131072
#else
#define USB_SERIAL_RX_BUFFER_BYTES 65536
#endif
#if STACKCHAN_DEVICE_STOPWATCH
#define USB_SERIAL_READ_BUDGET_BYTES 32768
#define USB_SERIAL_IDLE_DEFER_AFTER_PCM_MS 700
#else
#define USB_SERIAL_READ_BUDGET_BYTES 8192
#define USB_SERIAL_IDLE_DEFER_AFTER_PCM_MS 0
#endif
#define USB_SERIAL_CLIENT_TIMEOUT_MS 30000
#define USB_SERIAL_FRAME_MAX_PAYLOAD_BYTES 8192
#define USB_SERIAL_CAPTURE_CHUNK_BYTES 2048
#define CAMERA_JPEG_QUALITY 60
#define CAMERA_FRAME_SIZE FRAMESIZE_VGA
#define CAMERA_PIXEL_FORMAT PIXFORMAT_RGB565
#define CAMERA_FB_LOCATION CAMERA_FB_IN_PSRAM
#define CAMERA_BLE_SUSPEND_DMA_THRESHOLD_BYTES (48UL * 1024UL)
#define CAMERA_HTTP_WRITE_CHUNK_BYTES 2048
#define AUDIO_DIAG_LOG_ENABLED 0
#define USB_SERIAL_RX_DIAG_LOG_ENABLED 0
#define USB_SERIAL_TTS_DIAG_LOG_ENABLED 0
#define CAMERA_DIAG_LOG_ENABLED 0
#define FACE_DIAG_LOG_ENABLED 0
#define VERBOSE_LOG_ENABLED 0

#define DISPLAY_BRIGHTNESS_DEFAULT 160
#define DISPLAY_BRIGHTNESS_MIN 40
#define DISPLAY_BRIGHTNESS_MAX 255
#define DISPLAY_LOW_POWER_BRIGHTNESS_MAX 70
#define DISPLAY_CONVERSATION_BRIGHTNESS_PERCENT 85
#define AUDIO_SPEAKER_VOLUME_MIN 0
#if STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define AUDIO_SPEAKER_VOLUME_MAX 120
#else
#define AUDIO_SPEAKER_VOLUME_MAX 255
#endif
#define SETTINGS_STEP_VALUE 20
#ifndef THERMAL_FACE_EXPRESSION_ENABLED
// Keep thermal monitoring and low-power behavior active without replacing the face.
#define THERMAL_FACE_EXPRESSION_ENABLED 0
#endif
#define THERMAL_SAMPLE_INTERVAL_MS 10000
#define THERMAL_BASELINE_CAPTURE_MS 15000
#if STACKCHAN_DEVICE_ATOMS3R_CHATBOT
#define THERMAL_WARM_DELTA_C 18.0f
#define THERMAL_HOT_DELTA_C 28.0f
#define THERMAL_WARM_ABSOLUTE_C 70.0f
#define THERMAL_HOT_ABSOLUTE_C 82.0f
#define THERMAL_CHARGING_WARM_ABSOLUTE_C 72.0f
#define THERMAL_CHARGING_HOT_ABSOLUTE_C 84.0f
#define THERMAL_WARM_FACE_ENABLED 0
#else
#define THERMAL_WARM_DELTA_C 12.0f
#define THERMAL_HOT_DELTA_C 20.0f
#define THERMAL_WARM_ABSOLUTE_C 60.0f
#define THERMAL_HOT_ABSOLUTE_C 72.0f
#define THERMAL_CHARGING_WARM_ABSOLUTE_C 65.0f
#define THERMAL_CHARGING_HOT_ABSOLUTE_C 75.0f
#define THERMAL_WARM_FACE_ENABLED 1
#endif
#define THERMAL_LOW_POWER_SUGGEST_MS 30000
#define LOW_POWER_FACE_UPDATE_INTERVAL_MS 600
